[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.module]
source = "src/util.lua"
before = "main.lua"
name = "bearo.utils"

[[patches]]
[patches.pattern]
target = "engine/sprite.lua"
pattern = '''G.SHADERS[_shader or 'dissolve']:send("time",123.33412*(_draw_major.ID/1.14212 or 12.5123152)%3000)'''
position = "at"
payload = '''G.SHADERS[_shader or 'dissolve']:send("time", G.TIMERS.REAL)'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/sprite.lua"
pattern = '''G.SHADERS[_shader or 'dissolve']:send("mouse_screen_pos",self.ARGS.prep_shader.cursor_pos)'''
position = "at"
payload = '''G.SHADERS[_shader or 'dissolve']:send("mouse_screen_pos", love.mouse.getPosition())'''
match_indent = true